export const productCategories = [
  "Electronics",
  "Clothing",
  "Books",
  "Furniture",
  "Toys",
  "Groceries",
  "School Supplies",
  "Body Care Products",
  "Fashion",
  "Phone Accessories",
];

export const subCategories: { [key: string]: string[] } = {
  "School Supplies": [
    "Writing Instruments",
    "Paper Products",
    "Organizational Supplies",
    "Art and Craft Supplies",
    "Technology and Gadgets",
    "Classroom Essentials",
  ],
  "Body Care Products": [
    "Skincare",
    "Hair Care",
    "Oral Care",
    "Bath and Shower",
    "Deodorants and Antiperspirants",
    "Fragrances",
    "Shaving and Hair Removal",
    "Hand and Foot Care",
  ],
  Fashion: [
    "Clothing",
    "Footwear",
    "Accessories",
    "Undergarments",
    "Seasonal Wear",
    "Fashion Jewelry",
  ],
  "Phone Accessories": [
    "Protective Gear",
    "Charging Solutions",
    "Audio Accessories",
    "Mounts and Holders",
    "Connectivity",
    "Storage and Memory",
    "Photography Enhancements",
    "Wearables",
  ],
  Electronics: [
    "Mobile Phones",
    "Computers",
    "Tablets",
    "Televisions",
    "Cameras",
    "Audio Devices",
    "Wearable Technology",
    "Gaming Consoles",
  ],
  Clothing: [
    "Men's Clothing",
    "Women's Clothing",
    "Kid's Clothing",
    "Activewear",
    "Outerwear",
    "Sleepwear",
    "Formalwear",
  ],
  Books: [
    "Fiction",
    "Non-Fiction",
    "Educational",
    "Children's Books",
    "Comics",
    "Biographies",
    "Self-Help",
  ],
  Furniture: [
    "Living Room",
    "Bedroom",
    "Office",
    "Outdoor",
    "Storage",
    "Decor",
    "Lighting",
  ],
  Toys: [
    "Action Figures",
    "Puzzles",
    "Educational Toys",
    "Dolls",
    "Building Sets",
    "Outdoor Toys",
    "Video Games",
  ],
  Groceries: [
    "Fruits and Vegetables",
    "Dairy Products",
    "Beverages",
    "Snacks",
    "Bakery",
    "Frozen Foods",
    "Meat and Seafood",
  ],
};


export const possibleSizes = [
  "X-Small",
  "Small",
  "Medium",
  "Large",
  "X-Large",
  "One Size",
];